### ISSUE TITLE
PHP Notice - register_rest_route

### ISSUE THREAD

**Issue by markhowellsmead** [SayHelloGmbH/git-installer#27]
`Notice: Die Funktion register_rest_route wurde <strong>fehlerhaft aufgerufen</strong>. Der Definition der REST-API-Route für <code>git-installer/v1/git-packages-update/(?P<slug>\S+)</code> fehlt das erforderliche Argument <code>permission_callback</code>. Für REST-API-Routen, die für den öffentlichen Zugriff gedacht sind, benutzen Sie <code>__return_true</code> als Berechtigungs-Callback.`

**Comment by nico-martin** [comment]
Closed with https://github.com/SayHelloGmbH/git-installer/commit/e0091687657fd71d2a9414fcc756755c44045f38
