### ISSUE TITLE
Can't get this to run

### ISSUE THREAD

**Issue by Connum** [SayHelloGmbH/git-installer#37]
I wanted to give this a try, but I can't get it to work at all. With the plugin installed and activated, I created an access token. However, there was no `api` scope that I could select, as stated in the description text for GitHub repositories, no matter if creating a classic token or a fine-grained one. So I created a token with read-write access to every scope, but when entering that repository URL, all I get is an empty page in the admin backend. After trying to go to the second step. I even changed the access right to be able to access all repositories instead, but still the same.

Is there some documentation I'm missing?

Using WP 6.1.1  and trying to set up a private GitHub repo.

**Comment by nico-martin** [comment]
Yes, I described that wrong. It should be for the scope `repo`. I will adjust the description with the next release.

Would it be possible for you to give me access to your repository so I can recreate this on my end?

**Comment by Connum** [comment]
Thanks for the fast response! I created a token and I'll send it and the repo URL to you in a Twitter DM!

**Comment by nico-martin** [comment]
I just improved the link validation for the repositories a lot. With version 1.2.0 it will be possible to use any valid repository URL (SSH, HTTPS, URL anywhere in the repo,...)
