### ISSUE TITLE
Feature idea: Install from subdir - use subdirectory as theme folder name?

### ISSUE THREAD

**Issue by mandrasch** [SayHelloGmbH/git-installer#46]
Hey,

so cool to use this plugin for quick demo sites! Much appreciated, awesome work!

For a demo project I had this structure in my repo: `wp-content/wp-themes/twentytwentythree-child` 

After I installed the theme from subdirectory I was kind of suprised that the repository name was used instead of the subfolder name for the theme. 

(I do some pull actions from the live site to my local environment (via DDEV), therefore I ignore the subfolder of the child theme.)

Solved this currently by using the repository name as subfolder theme name by now, e.g.

https://github.com/mandrasch/train2lake-backend-wp => `wp-content/wp-themes/train2lake-backend-wp`

But maybe it would be cool for other people as well to use the actual theme folder name for a subfolder installation? 🤔 

Just as idea, please close if irrelevant / not planned.

Best regards,
Matthias
PS: And I noticed that https://www.git-installer.com/ is not added as URL to the repository settings here on Github. Just wanted to let you know.

**Comment by nico-martin** [comment]
Hi Matthias

That's a great idea! I already implemented it and it will be shipped with the next version 1.3.0 (currently in the `develop` branch). Will be published within the next days.

Kind regards,
Nico

**Comment by mandrasch** [comment]
Hey @nico-martin!

Wow, nice!! 🥳 🥳 🥳 

Best regards,
Matthias
