### ISSUE TITLE
Repo kann nicht gelöscht erden

### ISSUE THREAD

**Issue by markhowellsmead** [SayHelloGmbH/git-installer#54]
Falls das Repo direkt vom Server gelöscht wird, kann dieses nicht aus der Admin-Ansicht entfernt werden. Beim «Delete» betätigen wird nur eine Fehlermeldung angezeigt.

<img width="711" alt="Screenshot 2023-08-22 at 15 40 45" src="https://github.com/SayHelloGmbH/git-installer/assets/1571592/1a3aeee6-a7a3-4d0f-b861-e44863ba10e2">

**Comment by nico-martin** [comment]
Turned out to be an issue not related to git-installer
