### ISSUE TITLE
validateDOMNesting(...): <figure> cannot appear as a descendant of <p>.

### ISSUE THREAD

**Issue by markhowellsmead** [SayHelloGmbH/git-installer#56]
<img width="652" alt="Screenshot 2023-08-25 at 10 29 11" src="https://github.com/SayHelloGmbH/git-installer/assets/1571592/e84aacad-8318-4273-96ee-9a47d1b60874">

**Comment by nico-martin** [comment]
Solved with PR https://github.com/SayHelloGmbH/git-installer/pull/59
