### ISSUE TITLE
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.

### ISSUE THREAD

**Issue by markhowellsmead** [SayHelloGmbH/git-installer#61]
<img width="623" alt="Screenshot 2023-08-28 at 11 11 14" src="https://github.com/SayHelloGmbH/git-installer/assets/1571592/b4665327-67cb-4980-ba5f-3ed032b69ef0">

**Comment by nico-martin** [comment]
fixed with https://github.com/SayHelloGmbH/git-installer/pull/62
